services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default

  mailer:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - default

volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge
